# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'GladMinds'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.svg'
- name: BRAND_URL
  value: 'https://gladminds.co'
- name: WIDGET_BRAND_URL
  value: 'https://gladminds.co'
- name: BRAND_NAME
  value: 'GladMinds'
- name: TERMS_URL
  value: 'https://gladminds.co/terms'
- name: PRIVACY_URL
  value: 'https://gladminds.co/privacy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
